### PR TITLE
Update createDataset.py

### PR DESCRIPTION
**Pull request by rohith1125**
Set the encoding parameter "utf-8", to avoid conflict caused by Unicodes

### CODE REVIEW

**Comment by adeshpande3** [comment]
Couple Qs

1. Is there a reason this is just applied to 2 of the `open()` calls?
2. Could you explain what "avoid conflict caused by Unicodes" tactically means? What's the failure mode?

**Comment by rohith1125** [comment]
@adeshpande3 usually the texts contain emojis right, there was some error and few emojis weren't mapping properly unless we opened the file with UTF-8 encoding 

Was getting similar error if not opened with UTF-8 encoding,

unicodeencodeerror: 'charmap' codec can't encode characters in position

**Comment by adeshpande3** [comment]
Sounds good, could we also add that to the other `open` calls? I'm assuming we'd want it for the other data inputs if they have special characters too?

Also does it solve this issue? https://github.com/adeshpande3/Facebook-Messenger-Bot/issues/65

**Review by adeshpande3 — APPROVED** [review]
Pending the application to the other calls

**Comment by rohith1125** [comment]
> Sounds good, could we also add that to the other `open` calls? I'm assuming we'd want it for the other data inputs if they have special characters too?
> 
> Also does it solve this issue? #65

I think I've added that to the other `open` calls

**Comment by rohith1125** [comment]
> Sounds good, could we also add that to the other `open` calls? I'm assuming we'd want it for the other data inputs if they have special characters too?
> 
> Also does it solve this issue? #65

Well, that error was caused due to a specific unicode, even after opening it with UTF-8 encoding there are a few emojis that don't comply with the standard and misbehave, I would suggest including a function that filters out the uncommon characters and emojis

**Pull request merged**
