### PR TITLE
Update createDataset.py

### PR DESCRIPTION
**Pull request by rohith1125**
Replaced raw_input() with input() as raw_input() is no longer supported

### CODE REVIEW

**Review by adeshpande3 — APPROVED** [review]
Cool thanks! I'm assuming `input` is available for both Python2 and 3, while `raw_input` is only Python 2?

https://www.geeksforgeeks.org/difference-between-input-and-raw_input-functions-in-python/

**Comment by rohith1125** [comment]
@adeshpande3 yeah, and also need to add parenthesis for a few print statements

**Comment by adeshpande3** [comment]
Cool lgtm thank you :)

**Comment by rohith1125** [comment]
Merge? @adeshpande3

**Pull request merged**
